# Generated by Django 5.2.1 on 2025-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Chairman', 'Chairman'), ('Vice-Chancellor', 'Vice-Chancellor'), ('Dean', 'Dean')], max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='faculty_pics/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_building', models.CharField(blank=True, choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('B-3', 'B-3'), ('B-4', 'B-4')], max_length=100, null=True)),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_background', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('faculty_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
