# Generated by Django 5.2.1 on 2025-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, choices=[('EEE', 'EEE'), ('CSE', 'CSE'), ('BBA', 'BBA'), ('CIVIL', 'CIVIL'), ('Economics', 'Economics'), ('English', 'English')], max_length=100, null=True),
        ),
    ]
