# Generated by Django 5.2.1 on 2025-05-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_faculty_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('EEE', 'EEE'), ('CSE', 'CSE'), ('BBA', 'BBA'), ('CIVIL', 'CIVIL'), ('Economics', 'Economics'), ('English', 'English')], max_length=50, null=True)),
                ('intake', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('class_code', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.CharField(blank=True, choices=[('08:00 AM', '08:00 AM'), ('09:15 AM', '09:15 AM'), ('10:30 AM', '10:30 AM'), ('11:45 AM', '11:45 AM'), ('01:30 PM', '01:30 PM'), ('02:45 PM', '02:45 PM'), ('04:00 PM', '04:00 PM'), ('05:15 PM', '05:15 PM')], max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, choices=[('09:15 AM', '09:15 AM'), ('10:30 AM', '10:30 AM'), ('11:45 AM', '11:45 AM'), ('01:00 PM', '01:00 PM'), ('02:45 PM', '02:45 PM'), ('04:00 PM', '04:00 PM'), ('05:15 PM', '05:15 PM'), ('06:30 PM', '06:30 PM')], max_length=20, null=True)),
                ('day_name', models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=20, null=True)),
                ('date', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=2, null=True)),
                ('build_no', models.CharField(blank=True, choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('B-3', 'B-3'), ('B-4', 'B-4')], max_length=10, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
