# Generated by Django 5.2.1 on 2025-05-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_classroutine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroutine',
            options={'verbose_name_plural': 'Class Routine'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='position',
            field=models.CharField(blank=True, choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Chairman', 'Chairman'), ('Vice-Chancellor', 'Vice-Chancellor'), ('Dean', 'Dean')], max_length=50, null=True),
        ),
    ]
