# Generated by Django 5.2.1 on 2025-05-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0007_alter_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroutine',
            name='date',
        ),
    ]
