# Generated by Django 5.2.1 on 2026-04-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0011_student_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('building', models.CharField(choices=[('B-1', 'B-1'), ('B-2', 'B-2'), ('B-3', 'B-3'), ('B-4', 'B-4')], max_length=10)),
                ('capacity', models.IntegerField(default=50)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Classrooms',
                'ordering': ['building', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='routine.classroom')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_bookings', to='routine.faculty')),
            ],
            options={
                'verbose_name_plural': 'Classroom Bookings',
                'ordering': ['-booking_date', 'start_time'],
                'unique_together': {('classroom', 'booking_date', 'start_time')},
            },
        ),
    ]
