# Generated by Django 5.2.1 on 2026-04-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0012_classroom_classroombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('building', 'room_number')},
        ),
    ]
