# Generated by Django 5.2.1 on 2026-04-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0013_alter_classroom_room_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(help_text='Date for which attendance is being marked')),
                ('intake', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('num_classes', models.IntegerField(default=1, help_text='Number of classes taken on this date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='routine.classroutine')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='routine.faculty')),
            ],
            options={
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-attendance_date', '-created_at'],
                'unique_together': {('faculty', 'class_routine', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='routine.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='routine.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['student__student_name'],
                'unique_together': {('attendance', 'student')},
            },
        ),
    ]
