# Generated by Django 5.2.1 on 2026-04-14 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0017_populate_classroutine_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notice_type', models.CharField(choices=[('CT_DATE', 'CT Date'), ('ASSIGNMENT_DATE', 'Assignment Date'), ('IMPORTANT_NOTICE', 'Important Notice')], default='IMPORTANT_NOTICE', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='faculty_notices/')),
                ('posted_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='routine.classroutine')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='routine.faculty')),
            ],
            options={
                'verbose_name_plural': 'Faculty Notices',
                'ordering': ['-posted_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='routine.facultynotice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_notifications', to='routine.student')),
            ],
            options={
                'verbose_name_plural': 'Student Notifications',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'notice')},
            },
        ),
    ]
